apiVersion: apps/v1
kind: Deployment # 리소스의 종류
metadata:
  name: client-app
  namespace: team-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-app
  template:
    metadata:
      labels:
        app: client-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: alpha.eksctl.io/nodegroup-name
                operator: In
                values:
                - ng-2      
      containers:
      - name: client-app
        image: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/team-2:main-f7959af6079c5d986cb84fa6eef8f2c805dd823b #ECR 레파지토리
        imagePullPolicy: IfNotPresent
        resources:
          requests: #컨테이너가 어떤 자원을 가질것인지 정의
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 80 #컨테이너가 가지는 포트
--- 
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: team-2
spec:
  type: NodePort
  selector:
    app: client-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
