apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/team-2
  newTag: main-ae35ea59c20142c8ca62c5efe6b7aab7dcf02acd
- name: client-app
  newTag: main-51a4f738066794c064a3baa1b5205b392d0feef3
resources:
- ../../resources
