apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: /
  newName: /
- name: 686710509719.dkr.ecr.ap-northeast-2.amazonaws.com/team-2
  newTag: main-a7b37eae33c06445d5796013a35937d409ee3ca3
- name: client-app
  newTag: main-51a4f738066794c064a3baa1b5205b392d0feef3
resources:
- ../../resources
